# Default values for topology-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  provider:
    # name: "aws", "oci", "gcp", "nebius", "netq", "infiniband-k8s", "dra" or "test"
    name: infiniband-k8s
    params:
      nodeSelector:
        slurmCluster: my-cluster
      useGpuCliqueLabel: true
  engine:
    name: slinky
    params:
      namespace: slurm
      nodeSelector:
        slurmCluster: my-cluster
      podSelector:
        matchLabels:
          app.kubernetes.io/component: compute
      plugin: topology/block
      blockSizes: [4]
      useGpuCliqueLabel: true
      topologyConfigPath: topology.conf
      topologyConfigmapName: slurm-config

nodeSelector:
  dedicated: user-workload

tolerations:
  - operator: Exists

node-observer:
  nodeSelector:
    dedicated: user-workload
  topograph:
    trigger:
      podSelector:
        matchLabels:
          app.kubernetes.io/component: compute

node-data-broker:
  image:
    repository: ghcr.io/nvidia/topograph/ib
    pullPolicy: IfNotPresent
    tag: main
  initc:
    enabled: true
  verbosity: 4
  securityContext:
    privileged: true
  nodeSelector:
    node.dgxc.nvidia.com/has-gpu: "true"
  volumeMounts:
  - name: sys-class-volume
    mountPath: /sys/class
  volumes:
  - name: sys-class-volume
    hostPath:
      path: /sys/class
      type: Directory
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "present"
    effect: "NoSchedule"
